apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    purpose: api
spec:
  hostNetwork: true
  containers:
    - name: api
      image: registry.digitalocean.com/gitbid/api:d5c65b42
      ports:
        - containerPort: 8080
      env:
        - name: user
          value: "doadmin"
        - name: host
          value: "gitbook-postgres-do-user-7780289-0.b.db.ondigitalocean.com"
        - name: database
          value: "defaultdb"
        - name: password
          value: "b6y4az5p5hm862i7"
        - name: stripe
          value: "sk_test_51I7ulLHX1rk5bSX1MK50H6Dh0XUareNF98jfCZY6QT0Xxkek3btpPg4FpAHDD6RlUZxJjtJ3ryu2yqtmGxJ7Y1SG00EgWrpU48"
        - name: redisclienthost
          value: "db-redis-nyc1-23161-do-user-7780289-0.b.db.ondigitalocean.com"
        - name: redisclientport
          value: "25061"
        - name: rediesclientpassword
          value: "yrc09ub6yp78ztbv"
        - name: postgresport
          value: '25060'
        - name: github_client_id
          value: b3dec5a8697f01c59c74
        - name: github_client_secret
          value: 27fdc53ee5777185d9069501716eba84fd3d76f0