name: Docker

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: gitbid

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        run: docker build . -t registry.digitalocean.com/gitbid:${GITHUB_SHA::8} .
      - name: Publish Image to Container Registry
        uses: ripplr-io/docr-docker-publish@v1
        with:
          image_path: registry.digitalocean.com/gitbid:${GITHUB_SHA::8}
          sha_size: "8"
