name: Docker

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: gitbid

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: doctl registry login
      - name: Build Docker Image
        run: docker build . -t registry.digitalocean.com/gitbid/api:${GITHUB_SHA::8}
      - name: Publish Image to Container Registry
        run: docker push registry.digitalocean.com/gitbid/api:${GITHUB_SHA::8}
